version: '2'
services:
  jenkins:
    image: 'jenkins_mazerunner:1.0'
    links:
      - 'mosquitto:mosquitto'
      - 'sonarqube:qonarqube'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/bitnami'
    privileged: true
  sonarqube:
    image: 'sonarqube_mazerunner:1.0'
    ports:
      - '9000:9000'

  mosquitto:
    image: 'eclipse-mosquitto'
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - './mosquitto.conf:/mosquitto/config/mosquitto.conf'
volumes:
  jenkins_data:
    driver: local
