name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      COVERAGE_SINGLE: 60
      COVERAGE_TOTAL: 60

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: '1.6'
          ports: '1883:1883'
          container-name: 'mqtt'     
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: pytest
        id: pytest
        uses: alexanderdamiani/pytester-cov@v1.2.0
        with:
          pytest-root-dir: '.'
          cov-omit-list: 'Teams/ReferenceSolutionAStarCPP/*'
          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
      - name: Coverage total fail - new issue
        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Pytest coverage total falls below minimum ${{ env.COVERAGE_TOTAL }}
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: workflow-failed
          body: ${{ steps.pytester-cov.outputs.output-table }}
